services:
    employees-service:
        image: employees-service
        container_name: 'employees-service'
        build: ./
        command: ./app
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres
        container_name: 'postgres'
        restart: always
        shm_size: 512mb
        volumes:
            - ./migrations/:/docker-entrypoint-initdb.d/
        env_file:
            - .env
        ports:
            - 5432:5432
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
            interval: 3s
            timeout: 3s
            retries: 5

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
