services:
    employees-service:
        image: employees-service
        container_name: 'employees-service'
        build: ./
        command: ./app
        ports:
            - 8000:8000
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: 'postgres'
        restart: always
        shm_size: 512mb
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
